gesture swipe left  3 swaymsg workspace next_on_output
gesture swipe right 3 swaymsg workspace prev_on_output
gesture swipe up    3 /home/lukas/.config/sway/scripts/dmenu-toggle.sh open
gesture swipe down  3 /home/lukas/.config/sway/scripts/dmenu-toggle.sh close
