[ui]
styleset-name = opencode
sidebar-width = 24
mouse-enabled = true
sort = -r date
dirlist-delay = 200ms
dirlist-tree = true
threading-enabled = true
force-client-threads = false
sort-thread-siblings = false
index-columns = flags>4,date<14,name<26,subject<*
column-date = {{if .IsUnread}}{{.Style (dateFormat .Date.Local "02-01-06 15:04") "date-unread"}}{{else}}{{.Style (dateFormat .Date.Local "02-01-06 15:04") "date"}}{{end}}
column-name = {{if .IsUnread}}{{.Style .ThreadPrefix "sender-unread"}}{{.Style (index (.From | names) 0) "sender-unread"}}{{else}}{{.Style .ThreadPrefix "sender"}}{{.Style (index (.From | names) 0) "sender"}}{{end}}
column-flags = {{.Flags | join ""}}
column-subject = {{if .IsUnread}}{{.Style .ThreadPrefix "subject-unread"}}{{if .ThreadFolded}}{{.Style (printf "{%d}" .ThreadCount) "subject-unread"}}{{end}}{{.Style (or .Subject (.Header "Subject")) "subject-unread"}}{{else}}{{.Style .ThreadPrefix "subject"}}{{if .ThreadFolded}}{{.Style (printf "{%d}" .ThreadCount) "subject"}}{{end}}{{.Style (or .Subject (.Header "Subject")) "subject"}}{{end}}
icon-attachment = a
icon-new = N
icon-old = O
icon-replied = r
icon-flagged = !
icon-marked = *
icon-draft = d
icon-deleted = X

[viewer]
pager = less -Rc
alternatives = text/html,text/plain
parse-http-links = true

[filters]
text/plain = wrap -w 100 | colorize
text/html = w3m -T text/html -dump -cols 100 | colorize
message/delivery-status = colorize

[openers]
text/html = setsid -f gio open {}
image/* = ~/.config/aerc/scripts/open-image {}
application/pdf = setsid -f zathura {}
audio/* = setsid -f gio open {}
video/* = setsid -f gio open {}
message/rfc822 = setsid -f gio open {}
x-scheme-handler/http* = setsid -f gio open {}
x-scheme-handler/mailto = setsid -f gio open {}

[compose]
editor = nvim
header-layout = To|From,Subject
edit-headers = false

[statusline]
display-mode = text
